INSERT INTO data_newsAndEvent VALUES
	('','2010-11-24','AUTOBILD INDONESIA Magazine, edisi 198, 24 November - 7 Desember 2010, hal. 114.','AUTOBILD INDONESIA Magazine, Edisi 198, Hal. 114.','Ingin memasang kaca film? Mungkin layak mempertimbangkan window film yang satu ini, Berlabel Masterpiece..','News','101124_autobild.png','<img src="source/images/news/newspic/101124_news_autobild.jpg" width="100%"/>','1'),
	('','2010-12-14','CAR & TUNING GUIDE Magazine, edisi 397/XII/01, 14 Desember 2010, hal. 10.','CAR & TUNING GUIDE Magazine, edisi 397/XII/01, hal. 10.','Bertempat di Mall Summarecon Serpong (3/11), PT. Makko Raya Cemerlang meluncurkan kaca film Masterpiece. Dengan menggunakan teknologi..','News','101214_cartunningguide.png','<img src="source/images/news/newspic/101214_news_cartunningguide.jpg" width="100%"/>','1'),
	('','2010-12-02','TABLOID OTOMOTIF, edisi 31/XX, 02-08 Desember 2010, hal. 24.','TABLOID OTOMOTIF, edisi 31/XX, hal. 24','Klaimnya benar-benar bisa menolak panas dan digaransi tujuh tahun! Merek Masterpiece, produk made in Japan ini dibuat untuk iklim tropis. Sanggup menyaring panas hingga..','News','101202_otomotif.png','<img src="source/images/news/newspic/101202_otomotif.jpg" width="100%"/>','1'),
	('','2010-12-10','OTOSTEREO Magazine, edisi 91, 10 Des 2010 - 10 Jan 2011, hal. 108.','OTOSTEREO Magazine, edisi 91, hal. 108','Semakin maraknya kebutuhan untuk memenuhi kenyamanan berkendara dengan menggunakan rumah keduanya bagi siempunya mobil membuat para produsen otomotif selalu membuat innovasi terbaru..','News','101210_otostereo.png','<img src="source/images/news/newspic/101210_otostereo.jpg" width="100%"/>','1'),
	('','2011-01-19','AUTOBILD INDONESIA Magazine, edisi 202, 19 Januari - 1 Februari 2011, hal. 58.','AUTOBILD INDONESIA Magazine, edisi 202, hal. 58','Bisa dimengerti mengapa tren penggunaan windowfilm semakin meningkat. Lembaran film pelapis kaca ini memiliki sejumlah kelebihan yang menari untuk di timang. Sebut saja sebagai..','News','110119_autobild.png','<img src="source/images/news/newspic/110119_autobild.jpg" width="100%"/>','1'),
	('','2011-01-20','TABLOID OTOMOTIF, edisi 38/XX, 20-26 Januari 2011, Sisipan OTOBURSA, hal. 01.','TABLOID OTOMOTIF, edisi 38/XX, Sisipan OTOBURSA, hal. 01','Mau pasang kaca fil yang bisa menolak panas dan bergaransi cukup lama? Bisa Anda sambangi Jaya Lestari Makmur di Jl. Raya Kelapa Dua, Ruko PDA No.2 Gading Serpong..','News','110120_otomotif.png','<img src="source/images/news/newspic/110120_otomotif.jpg" width="100%"/>','1'),
	('','2011-03-03','TABLOID OTOMOTIF, edisi 44/XX, 03 - 09 Maret 2011, hal. 24.','TABLOID OTOMOTIF, edisi 44/XX, hal. 24.','Berlabel Masterpiece, kaca film buatan Negeri Sakura ini punya produk unggulan: Renzu Mint 45 (30%) dan Renzu Mint 15 (70%). Kedua tipe ini berwarna hitam solid, dengan tingkat kegelapan yang berbeda..','News','110303_otomotif.png','<img src="source/images/news/newspic/110303_otomotif.jpg" width="100%"/>','1'),
	('','2011-03-25','Masterpiece Renzu Mint: Kaca Film Premium untuk Mobil by DAPURPACU.COM, 25 Maret 2011.','Masterpiece Renzu Mint: Kaca Film Premium untuk Mobil by DAPURPACU.COM','Bagi Anda yang tengah mencari kaca film mobil, Masterpiece Renzu Mint bisa menjadi pilihan. Masterpiece diproduksi di Jepang dan menggunakan..','News','110325_dapurpacu.png','<img src="source/images/news/newspic/110325_dapurpacu.jpg" width="100%"/>','1'),
	('','2011-03-26','Masterpiece Renzu Mint: Cegah Sengatan Matahari sampai 99 Persen by KOMPAS.COM, 26 Maret 2011.','Masterpiece Renzu Mint: Cegah Sengatan Matahari sampai 99 Persen by KOMPAS.COM','Bagi pemilik  mobil, peran kaca film atau lapisan kaca, cukup penting. Terutama  saat cuaca sangat terik..','News','110326_kompas.png','<img src="source/images/news/newspic/110326_kompas.jpg" width="100%"/>','1'),
	('','2011-03-26','','','','News','','','1'),
	('','2011-03-26','','','','News','','','1'),
	('','2011-03-28','','','','News','','','1'),
	('','2011-03-28','','','','News','','','1'),
	('','2011-03-29','','','','News','','','1'),
	('','2011-03-29','','','','News','','','1'),
	('','2011-03-31','','','','News','','','1'),
	('','2011-04-07','','','','News','','','1'),
	('','2011-04-01','','','','News','','','1'),
	('','2011-04-20','','','','News','','','1'),
	('','2011-04-01','','','','News','','','1'),
	('','2011-04-20','','','','News','','','1'),
	('','2011-03-13','','','','News','','','1'),
	('','2011-05-01','','','','News','','','1'),
	('','2011-05-01','','','','News','','','1'),
	('','2011-05-01','','','','News','','','1'),
	('','2011-05-05','','','','News','','','1'),
	('','2011-05-18','','','','News','','','1'),
	('','2011-05-01','','','','News','','','1'),
	('','2011-07-29','','','','News','','','1'),
	('','2011-07-30','','','','News','','','1'),
	('','2011-08-18','','','','News','','','1'),
	('','2011-08-01','','','','News','','','1'),
	('','2011-10-06','','','','News','','','1'),
	('','2011-12-22','','','','News','','','1'),
	('','2012-02-10','','','','News','','','1'),
	('','2012-05-31','','','','News','','','1'),
	('','2012-09-21','','','','News','','','1');
	
INSERT INTO data_newsAndEvent VALUES
	('','2010-11-14','[2010-11-14] MASTERPIECE Autofever Exhibition @ Summarecon Mall Serpong.','MASTERPIECE Autofever Exhibition @ Summarecon Mall Serpong','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2010-12-19','[2010-12-19] TREND AUTO @ Supermall Karawaci, Centre Court Lantai Dasar.','TREND AUTO @ Supermall Karawaci, Centre Court Lantai Dasar','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2011-05-21','[2011-05-21] Pameran OTOBURSA Tumplek Blek @ Plaza & Parkir Timur Gelora Bung Karno.','Pameran OTOBURSA Tumplek Blek @ Plaza & Parkir Timur Gelora Bung Karno','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2011-07-22','[2011-07-22] INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo Kemayoran - Jakarta.','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo Kemayoran - Jakarta','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2011-10-12','[2011-10-12] TREND AUTO @ Supermall Karawaci, West Atrium Hall.','TREND AUTO @ Supermall Karawaci, West Atrium Hall','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-01-15','[2012-01-15] AUTO TREND @ Supermall Karawaci, Center Court.','AUTO TREND @ Supermall Karawaci, Center Court','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-02-05','[2012-02-05] AUTO FIESTA @ Mall Emporium, West Atrium.','AUTO FIESTA @ Mall Emporium, West Atrium','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-03-04','[2012-03-04] AUTOMOTIVE FAIR @ Summarecon Mall Serpong 1.','AUTOMOTIVE FAIR @ Summarecon Mall Serpong 1','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-09-20','[2012-09-20] THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo Kemayoran - Jakarta', 'THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo Kemayoran - Jakarta' ,'NO DESCRIPTION','Events','NO PICTURE','','1');
	
	
INSERT INTO data_picTable VALUES
	('9','THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo','120920_IIMS_01.png','120920_IIMS_01.jpg','1'),
	('9','THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo','120920_IIMS_02.png','120920_IIMS_02.jpg','1'),

	('8','AUTOMOTIVE FAIR @ Summarecon Mall Serpong 1','120304_automotivefair_01.png','120304_automotivefair_01.jpg','1'),

	('7','AUTO FIESTA @ Mall Emporium, West Atrium','120205_autofiesta_01.png','120205_autofiesta_01.jpg','1'),
	
	('6','TREND AUTO @ Supermall Karawaci','120115_autotrend_01.png','120115_autotrend_01.jpg','1'),

	('5','TREND AUTO @ Supermall Karawaci','111012_trendauto_01.png','111012_trendauto_01.jpg','1'),
	('5','TREND AUTO @ Supermall Karawaci','111012_trendauto_02.png','111012_trendauto_02.jpg','1'),

	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_01.png','110722_intmotorshow_01.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_02.png','110722_intmotorshow_02.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_03.png','110722_intmotorshow_03.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_04.png','110722_intmotorshow_04.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_05.png','110722_intmotorshow_05.jpg','1'),
	
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_01.png','110521_otobursa_01.jpg','1'),
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_02.png','110521_otobursa_02.jpg','1'),
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_03.png','110521_otobursa_03.jpg','1'),
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_04.png','110521_otobursa_04.jpg','1'),

	('2','TREND AUTO, @ Supermall Karawaci, Centre Court Lantai Dasar','101219_trendauto_01.png','101219_trendauto_01.jpg','1'),
	('2','TREND AUTO, @ Supermall Karawaci, Centre Court Lantai Dasar','101219_trendauto_02.png','101219_trendauto_02.jpg','1'),
	('2','TREND AUTO, @ Supermall Karawaci, Centre Court Lantai Dasar','101219_trendauto_03.png','101219_trendauto_03.jpg','1'),
	
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_01.png','101114_autofever_01.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_02.png','101114_autofever_02.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_03.png','101114_autofever_03.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_04.png','101114_autofever_04.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_05.png','101114_autofever_05.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_06.png','101114_autofever_06.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_07.png','101114_autofever_07.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_08.png','101114_autofever_08.jpg','1');
