INSERT INTO data_newsAndEvent VALUES
	('','2010-11-24','AUTOBILD INDONESIA Magazine, edisi 198, 24 November - 7 Desember 2010, hal. 114.','AUTOBILD INDONESIA Magazine, Edisi 198, Hal. 114.','Ingin memasang kaca film? Mungkin layak mempertimbangkan window film yang satu ini, Berlabel Masterpiece..','News','101124_autobild.png','<img src="source/images/news/newspic/101124_news_autobild.jpg" width="100%"/>','1'),
	('','2010-12-14','CAR & TUNING GUIDE Magazine, edisi 397/XII/01, 14 Desember 2010, hal. 10.','CAR & TUNING GUIDE Magazine, edisi 397/XII/01, hal. 10.','Bertempat di Mall Summarecon Serpong (3/11), PT. Makko Raya Cemerlang meluncurkan kaca film Masterpiece. Dengan menggunakan teknologi..','News','101214_cartunningguide.png','<img src="source/images/news/newspic/101214_news_cartunningguide.jpg" width="100%"/>','1'),
	('','2010-12-02','TABLOID OTOMOTIF, edisi 31/XX, 02-08 Desember 2010, hal. 24.','TABLOID OTOMOTIF, edisi 31/XX, hal. 24','Klaimnya benar-benar bisa menolak panas dan digaransi tujuh tahun! Merek Masterpiece, produk made in Japan ini dibuat untuk iklim tropis. Sanggup menyaring panas hingga..','News','101202_otomotif.png','<img src="source/images/news/newspic/101202_otomotif.jpg" width="100%"/>','1'),
	('','2010-12-10','OTOSTEREO Magazine, edisi 91, 10 Des 2010 - 10 Jan 2011, hal. 108.','OTOSTEREO Magazine, edisi 91, hal. 108','Semakin maraknya kebutuhan untuk memenuhi kenyamanan berkendara dengan menggunakan rumah keduanya bagi siempunya mobil membuat para produsen otomotif selalu membuat innovasi terbaru..','News','101210_otostereo.png','<img src="source/images/news/newspic/101210_otostereo.jpg" width="100%"/>','1'),
	('','2011-01-19','AUTOBILD INDONESIA Magazine, edisi 202, 19 Januari - 1 Februari 2011, hal. 58.','AUTOBILD INDONESIA Magazine, edisi 202, hal. 58','Bisa dimengerti mengapa tren penggunaan windowfilm semakin meningkat. Lembaran film pelapis kaca ini memiliki sejumlah kelebihan yang menari untuk di timang. Sebut saja sebagai..','News','110119_autobild.png','<img src="source/images/news/newspic/110119_autobild.jpg" width="100%"/>','1'),
	('','2011-01-20','TABLOID OTOMOTIF, edisi 38/XX, 20-26 Januari 2011, Sisipan OTOBURSA, hal. 01.','TABLOID OTOMOTIF, edisi 38/XX, Sisipan OTOBURSA, hal. 01','Mau pasang kaca fil yang bisa menolak panas dan bergaransi cukup lama? Bisa Anda sambangi Jaya Lestari Makmur di Jl. Raya Kelapa Dua, Ruko PDA No.2 Gading Serpong..','News','110120_otomotif.png','<img src="source/images/news/newspic/110120_otomotif.jpg" width="100%"/>','1'),
	('','2011-03-03','TABLOID OTOMOTIF, edisi 44/XX, 03 - 09 Maret 2011, hal. 24.','TABLOID OTOMOTIF, edisi 44/XX, hal. 24.','Berlabel Masterpiece, kaca film buatan Negeri Sakura ini punya produk unggulan: Renzu Mint 45 (30%) dan Renzu Mint 15 (70%). Kedua tipe ini berwarna hitam solid, dengan tingkat kegelapan yang berbeda..','News','110303_otomotif.png','<img src="source/images/news/newspic/110303_otomotif.jpg" width="100%"/>','1'),
	('','2011-03-25','Masterpiece Renzu Mint: Kaca Film Premium untuk Mobil by DAPURPACU.COM, 25 Maret 2011.','Masterpiece Renzu Mint: Kaca Film Premium untuk Mobil by DAPURPACU.COM','Bagi Anda yang tengah mencari kaca film mobil, Masterpiece Renzu Mint bisa menjadi pilihan. Masterpiece diproduksi di Jepang dan menggunakan..','News','110325_dapurpacu.png','<img src="source/images/news/newspic/110325_dapurpacu.jpg" width="100%"/>','1'),
	('','2011-03-26','Masterpiece Renzu Mint: Cegah Sengatan Matahari sampai 99 Persen by KOMPAS.COM, 26 Maret 2011.','Masterpiece Renzu Mint: Cegah Sengatan Matahari sampai 99 Persen by KOMPAS.COM','Bagi pemilik  mobil, peran kaca film atau lapisan kaca, cukup penting. Terutama  saat cuaca sangat terik..','News','110326_kompas.png','<img src="source/images/news/newspic/110326_kompas.jpg" width="100%"/>','1'),
	('','2011-03-26','Nih Masterpiece, Kaca Film Premium, Anti Panas! by OTOMOTIFNET.COM, 26 Maret 2011.','Nih Masterpiece, Kaca Film Premium, Anti Panas! by OTOMOTIFNET.COM','','News','','','1'),
	('','2011-03-26','Masterpiece Renzu Mint Dirilis by AUTOBILDINDONESIA.COM,26 Maret 2011.','Masterpiece Renzu Mint Dirilis by AUTOBILDINDONESIA.COM','','News','','','1'),
	('','2011-03-28','Masterpiece Teknologi Baru Kaca Film by MARKET+ MAGAZINE, 28 Maret 2011.','Masterpiece Teknologi Baru Kaca Film by MARKET+ MAGAZINE','','News','','','1'),
	('','2011-03-28','KORAN WARTA KOTA, Senin, 28 Maret 2011.','KORAN WARTA KOTA, Senin, 28 Maret 2011','','News','','','1'),
	('','2011-03-29','Peluncuran Kaca Film Masterpiece Renzu Mint by BosMobil, 29 Maret 2011.','Peluncuran Kaca Film Masterpiece Renzu Mint by BosMobil','','News','','','1'),
	('','2011-03-29','Masterpiece Luncurkan 2 Varian Terbaru by HIN ( Hot Import Night ), 29 Maret 2011.','Masterpiece Luncurkan 2 Varian Terbaru by HIN ( Hot Import Night )','','News','','','1'),
	('','2011-03-31','TABLOID OTOMOTIF, edisi 390, 31 Maret - 06 April 2011, Sisipan OTOMOTIF, hal. 03.','TABLOID OTOMOTIF, edisi 390, Sisipan OTOMOTIF, hal. 03','','News','','','1'),
	('','2011-04-07','TABLOID OTOMOTIF edisi 49:XX, O7-13 April 2011, hal. 31.','TABLOID OTOMOTIF edisi 49:XX, åhal. 31','','News','','','1'),
	('','2011-04-01','MOTOR TREND MAGAZINE, edisi April 2011, hal. 21.','MOTOR TREND MAGAZINE, edisi April 2011, hal. 21','','News','','','1'),
	('','2011-04-20','CAR & TUNING GUIDE MAGAZINE, edisi 407/XII/20 April - 03 Mei 2011, hal. 16.','CAR & TUNING GUIDE MAGAZINE, edisi 407/XII/20 hal. 16','','News','','','1'),
	('','2011-04-01','OTOSTEREO Magazine, Edisi 95, April - Mei 2011, hal. 113.','OTOSTEREO Magazine, Edisi 95, hal. 113','','News','','','1'),
	('','2011-04-20','MOBIL MOTOR MAGAZINE, edisi No. 08/XLI/20 April - 3 Mei 2011, hal. 17.','MOBIL MOTOR MAGAZINE, edisi No. 08/XLI/20, hal. 17','','News','','','1'),
	('','2011-03-13','AUTOBILD MAGAZINE, edisi 208, 13 - 26 April 2011, hal. 76.','AUTOBILD MAGAZINE, edisi 208, hal. 76','','News','','','1'),
	('','2011-05-01','AUTOCAR MAGAZINE, edisi May 2011, hal. 118.','AUTOCAR MAGAZINE, hal. 118','','News','','','1'),
	('','2011-05-01','MODIFIKASI PLUS MAGAZINE, edisi 48/IV/May 2011, hal. 77.','MODIFIKASI PLUS MAGAZINE, edisi 48/IV/May 2011, hal. 77','','News','','','1'),
	('','2011-05-01','OTOSTEREO MAGAZINE, edisi 96, May - June 2011, hal. 41.','OTOSTEREO MAGAZINE, edisi 96, hal. 41','','News','','','1'),
	('','2011-05-05','TABLOID OTOMOTIF, edisi Khusus Ulang Tahun, NO.01/XXI, 05-11 May 2011, hal. 63.','TABLOID OTOMOTIF, edisi Khusus Ulang Tahun, NO.01/XXI, hal. 63 ','','News','','','1'),
	('','2011-05-18','CAR & TUNING GUIDE MAGAZINE, edisi 409/XII/18 - 31 May 2011, hal. 19.','CAR & TUNING GUIDE MAGAZINE, edisi 409/XII/18 - 31 May 2011, hal. 19','','News','','','1'),
	('','2011-05-01','DRIVEN - HOT IMPORT NIGHT MAGAZINE, edisi 29, May 2011, hal. 34.','DRIVEN - HOT IMPORT NIGHT MAGAZINE, edisi 29, hal. 34','','News','','','1'),
	('','2011-07-29','Masterpiece Window Film di IIMS 2011 by BOSMOBIL.COM, 29 July 2011.','Masterpiece Window Film di IIMS 2011 by BOSMOBIL.COM','','News','','','1'),
	('','2011-07-30','Masterpiece: Kaca Film Kualitas Teratas Dengan Harga Terjangkau by EYANXJENDRAL.COM, 30 July 2011.','Masterpiece: Kaca Film Kualitas Teratas Dengan Harga Terjangkau by EYANXJENDRAL.COM','','News','','','1'),
	('','2011-08-18','TABLOID OTOMOTIF, edisi No. 16/XXI, 18 - 24 Agustus 2011, Sisipan OTOBURSA hal. 06.','TABLOID OTOMOTIF, edisi No. 16/XXI, Sisipan OTOBURSA hal. 06','','News','','','1'),
	('','2011-08-01','OTOSTEREO MAGAZINE, edisi 99, Agustus - September 2011, hal. 99.','OTOSTEREO MAGAZINE, edisi 99, hal. 99.','','News','','','1'),
	('','2011-10-06','TABLOID OTOMOTIF, edisi 23:XXI, 06 - 12 Oktober 2011, hal. 31.','TABLOID OTOMOTIF, edisi 23:XXI, hal. 31.','','News','','','1'),
	('','2011-12-22','TABLOID OTOMOTIF, edisi 34:XXI, 22 - 28 Desember 2011, hal. 24.','TABLOID OTOMOTIF, edisi 34:XXI, hal. 24.','','News','','','1'),
	('','2012-02-10','OTOSTEREO MAGAZINE, edisi 104, 10 Februari - 10 Maret 2012, hal 68 - 69.','OTOSTEREO MAGAZINE, edisi 104, hal 68 - 69.','','News','','','1'),
	('','2012-05-31','Tabloid OTOMOTIF, edisi 451, 31 Mei - 6 Juni 2012, Sisipan OTOBURSA, hal. 06','Tabloid OTOMOTIF, edisi 451, Sisipan OTOBURSA, hal. 06','','News','','','1'),
	('','2012-09-21','Tabloid OTOSTEREO, Tips Pemasangan Kaca Film MASTERPIECE','Tabloid OTOSTEREO, Tips Pemasangan Kaca Film MASTERPIECE','','News','','','1');
	
INSERT INTO data_newsAndEvent VALUES
	('','2010-11-14','[2010-11-14] MASTERPIECE Autofever Exhibition @ Summarecon Mall Serpong.','MASTERPIECE Autofever Exhibition @ Summarecon Mall Serpong','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2010-12-19','[2010-12-19] TREND AUTO @ Supermall Karawaci, Centre Court Lantai Dasar.','TREND AUTO @ Supermall Karawaci, Centre Court Lantai Dasar','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2011-05-21','[2011-05-21] Pameran OTOBURSA Tumplek Blek @ Plaza & Parkir Timur Gelora Bung Karno.','Pameran OTOBURSA Tumplek Blek @ Plaza & Parkir Timur Gelora Bung Karno','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2011-07-22','[2011-07-22] INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo Kemayoran - Jakarta.','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo Kemayoran - Jakarta','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2011-10-12','[2011-10-12] TREND AUTO @ Supermall Karawaci, West Atrium Hall.','TREND AUTO @ Supermall Karawaci, West Atrium Hall','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-01-15','[2012-01-15] AUTO TREND @ Supermall Karawaci, Center Court.','AUTO TREND @ Supermall Karawaci, Center Court','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-02-05','[2012-02-05] AUTO FIESTA @ Mall Emporium, West Atrium.','AUTO FIESTA @ Mall Emporium, West Atrium','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-03-04','[2012-03-04] AUTOMOTIVE FAIR @ Summarecon Mall Serpong 1.','AUTOMOTIVE FAIR @ Summarecon Mall Serpong 1','NO DESCRIPTION','Events','NO PICTURE','','1'),
	('','2012-09-20','[2012-09-20] THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo Kemayoran - Jakarta', 'THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo Kemayoran - Jakarta' ,'NO DESCRIPTION','Events','NO PICTURE','','1');
	
	
INSERT INTO data_picTable VALUES
	('9','THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo','120920_IIMS_01.png','120920_IIMS_01.jpg','1'),
	('9','THE 20th INTERNATIONAL INDONESIA MOTOR SHOW ( IIMS ) 2012, @JIExpo','120920_IIMS_02.png','120920_IIMS_02.jpg','1'),

	('8','AUTOMOTIVE FAIR @ Summarecon Mall Serpong 1','120304_automotivefair_01.png','120304_automotivefair_01.jpg','1'),

	('7','AUTO FIESTA @ Mall Emporium, West Atrium','120205_autofiesta_01.png','120205_autofiesta_01.jpg','1'),
	
	('6','TREND AUTO @ Supermall Karawaci','120115_autotrend_01.png','120115_autotrend_01.jpg','1'),

	('5','TREND AUTO @ Supermall Karawaci','111012_trendauto_01.png','111012_trendauto_01.jpg','1'),
	('5','TREND AUTO @ Supermall Karawaci','111012_trendauto_02.png','111012_trendauto_02.jpg','1'),

	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_01.png','110722_intmotorshow_01.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_02.png','110722_intmotorshow_02.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_03.png','110722_intmotorshow_03.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_04.png','110722_intmotorshow_04.jpg','1'),
	('4','INDONESIA INTERNATIONAL MOTOR SHOW ( IIMS ) 2011 @ JIExpo','110722_intmotorshow_05.png','110722_intmotorshow_05.jpg','1'),
	
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_01.png','110521_otobursa_01.jpg','1'),
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_02.png','110521_otobursa_02.jpg','1'),
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_03.png','110521_otobursa_03.jpg','1'),
	('3','Pameran OTOBURSA Tumplek Blek, @Plaza & Parkir Timur Gelora Bung Karno','110521_otobursa_04.png','110521_otobursa_04.jpg','1'),

	('2','TREND AUTO, @ Supermall Karawaci, Centre Court Lantai Dasar','101219_trendauto_01.png','101219_trendauto_01.jpg','1'),
	('2','TREND AUTO, @ Supermall Karawaci, Centre Court Lantai Dasar','101219_trendauto_02.png','101219_trendauto_02.jpg','1'),
	('2','TREND AUTO, @ Supermall Karawaci, Centre Court Lantai Dasar','101219_trendauto_03.png','101219_trendauto_03.jpg','1'),
	
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_01.png','101114_autofever_01.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_02.png','101114_autofever_02.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_03.png','101114_autofever_03.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_04.png','101114_autofever_04.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_05.png','101114_autofever_05.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_06.png','101114_autofever_06.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_07.png','101114_autofever_07.jpg','1'),
	('1','MASTERPIECE Autofever Exhibition, @Summarecon Mall Serpong','101114_autofever_08.png','101114_autofever_08.jpg','1');
